version: '3.8'

services:
  memory-memo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - memo_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/memory_memo.db
      - PORT=3000
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  memo_data:
    driver: local